# Example: Trigger review with @agent-review comment
name: Comment-Triggered Review

on:
  issue_comment:
    types: [created]

jobs:
  review:
    # Only run if comment contains @agent-review and is on a PR
    if: |
      github.event.issue.pull_request &&
      contains(github.event.comment.body, '@agent-review')

    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: React to comment
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.reactions.createForIssueComment({
              ...context.repo,
              comment_id: context.payload.comment.id,
              content: 'eyes'
            });

      - uses: actions/checkout@v4
        with:
          ref: refs/pull/${{ github.event.issue.number }}/head

      - name: AI Code Review
        uses: your-org/code-review-agent@v1
        with:
          anthropic-api-key: ${{ secrets.ANTHROPIC_API_KEY }}
          comment-on-pr: 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
