name: 'AI Code Review Agent'
description: 'Automated code review using Claude AI Agent SDK'
author: 'Code Review Agent Team'
branding:
  icon: 'check-circle'
  color: 'blue'

inputs:
  anthropic-api-key:
    description: 'Anthropic API key for Claude'
    required: true

  target:
    description: 'Target file or directory to review'
    required: false
    default: '.'

  model:
    description: 'Claude model to use'
    required: false
    default: 'claude-sonnet-4.5-20250929'

  max-budget:
    description: 'Maximum budget in USD'
    required: false
    default: '5.0'

  max-files:
    description: 'Maximum number of files to review'
    required: false
    default: '50'

  severity-threshold:
    description: 'Minimum severity level to report (info, warning, error, critical)'
    required: false
    default: 'info'

  include-patterns:
    description: 'File patterns to include (comma-separated)'
    required: false
    default: '**/*.ts,**/*.js,**/*.tsx,**/*.jsx'

  exclude-patterns:
    description: 'Additional file patterns to exclude (comma-separated)'
    required: false
    default: ''

  output-format:
    description: 'Output format (console, json, markdown)'
    required: false
    default: 'markdown'

  fail-on-critical:
    description: 'Fail the action if critical issues are found'
    required: false
    default: 'true'

  fail-on-error:
    description: 'Fail the action if errors are found'
    required: false
    default: 'false'

  comment-on-pr:
    description: 'Post review results as a PR comment'
    required: false
    default: 'true'

outputs:
  status:
    description: 'Review status (success, partial, failure)'

  total-issues:
    description: 'Total number of issues found'

  critical-count:
    description: 'Number of critical issues'

  error-count:
    description: 'Number of errors'

  warning-count:
    description: 'Number of warnings'

  report-file:
    description: 'Path to the generated report file'

runs:
  using: 'node20'
  main: 'dist/action.js'
