# AI Code Review Workflow
#
# Simple, fast, drop-in code review using AI
# Just copy this file and add your ANTHROPIC_API_KEY secret
#
# Setup:
# 1. Add this file to: .github/workflows/ai-code-review.yml
# 2. Add ANTHROPIC_API_KEY to repository secrets
# 3. Create a PR - Done!

name: AI Code Review

on:
  pull_request:
    types: [opened, synchronize, reopened]
  issue_comment:
    types: [created]

jobs:
  code-review:
    # Run on PR events OR when @agent-review is commented
    if: |
      github.event_name == 'pull_request' ||
      (github.event.issue.pull_request && contains(github.event.comment.body, '@agent-review'))

    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout PR Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1  # Fast checkout for PR diff analysis

      - name: AI Code Review
        uses: Hussain-7/github-code-review-action@v1
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          max-budget: '5.0'
          severity-threshold: 'warning'
          fail-on: 'critical'
